% bootstrp_jo(bootfun,Ox,Oy,R)
%   Bootstrap method for estimating the confidence limits
%   of the fit parameters for the data set (Ox,Oy) when the
%   underlying probability distribution of the errors in 
%   unknown (see e.g. Press et al 1988; Manly, 1991).
%
%   This function returns a series of R fit parameters
%   for the original data set (Ox,Oy). The fit function 
%   used is given by 'bootfun'.
%
%   The mean value and standard deviation of a parameter 
%   (eg 1) is given by mean(pars(:,1)) and std(pars(:,1))
%
%   pars=bootstrp(bootfun,Ox,Oy,R);   
%      calls some function par=bootfun(x,y)
%
%   Jeroen Goossens

function pars=bootstrp_jo(bootfun,Ox,Oy,R)

N = length(Oy);
for i=1:R,
   % select from the measured set of N data points a new 
   % hypothetical data set which is generated by randomly 
   % drawing, with uniform probability,  N points from the
   % original data set. 
   s = floor( (N-1) * rand([N,1]) ) + 1;
   Hx=Ox(s);
   Hy=Oy(s);
   eval([ 'par = ' bootfun '(Hx,Hy);']);
   pars(i,:) = par;
end;
